### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by raulsoria98** [CriptoInfo/CryptoGo#10]
Decidir el lenguaje que vamos a utilizar para la aplicación

**Comment by migue0418** [comment]
Podríamos usar el lenguaje Golang ya que tiene tipado fuerte.

**Comment by agr8** [comment]
Sería una buena oportunidad para aprender Golang.

**Comment by raulsoria98** [comment]
Pues yo había pensado en Raku que es un lenguaje muy interesante, pero si ambos estáis a favor de Golang, podemos utilizar Go

**Comment by migue0418** [comment]
Vale, pues Golang entonces.
